variables:
  service_name: personal-demographics
  short_service_name: pds
  service_base_path: personal-demographics
  product_display_name: Personal Demographics Service
  product_description: Placeholder description
  idp_url: https://nhsd-apim-testing-internal-dev.herokuapp.com
