version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt install python3 default-jre default-jdk
            make install
      - run:
          name: Lint spec
          command: make test
      - run:
          name: Check resources are valid FHIR 4.0.1
          command: make validate || true
      - run:
          name: Compile spec
          command: make publish
      - store_artifacts:
          path: ./dist/patient-information-api.json
      - run:
          name: Upload artifacts to bitbucket
          command: |
            cp ./dist/patient-information-api.json /tmp/patient-information-api-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}.json
            curl --fail -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/laurencesmith/apim-definitions/downloads" --form files=@"/tmp/patient-information-api-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}.json"
      - run:
          name: Deploy to Apigee (if master)
          command: scripts/deploy.sh
