version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: make test
      - run: make release
      - store_artifacts:
          path: ./public/patient-information-api.json
      - run: curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/laurencesmith/apim-definitions/downloads" --form files=@"./public/patient-information-api.json"
