version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: make test
      - run: make release
      - store_artifacts:
          path: ./public/patient-information-api.json
