steps:
  - bash: |
      APPLICATION_RESTRICTED_SIGNING_KEY_PATH="$(Pipeline.Workspace)/secrets/$(JWT_TESTING_PRIVATE_KEY)"
      APPLICATION_RESTRICTED_API_KEY="$(JWT_TESTING_API_KEY)"
      PDS_BASE_PATH="$(SERVICE_BASE_PATH)"
      APIGEE_ENVIRONMENT="$(ENVIRONMENT)"
      KEY_ID="test-1"

      poetry run pytest -v functional/test_application_restricted.py --junitxml=functional-test-report.xml
    displayName: Run applcation restricted tests
    workingDirectory: "$(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/tests"
  
  - task: PublishTestResults@2
    displayName: 'Publish application restricted test results'
    inputs:
      testResultsFiles: $(Pipeline.Workspace)/s/$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/tests/functional-test-report.xml
      failTaskOnFailedTests: true