name: application-restricted # Will have SERVICE_NAME- prepended to this
displayName: Personal Demographics Service - Application Restricted - Prod Rate Limit
description: Access the Personal Demographics Service with reduced permisions.
environments:
  - internal-dev-sandbox
attributes:
  - name: access
    value: public
  - name: ratelimit
    value: 130ps
quota: 7800
quotaInterval: 1
quotaTimeUnit: minute
