name: application-restricted # Will have SERVICE_NAME- prepended to this
displayName: Personal Demographics Service - Application Restricted
description: Access the Personal Demographics Service with reduced permisions.
environments:
  - prod
  - ref
attributes:
  - name: access
    value: public
  - name: ratelimit
    value: 7800pm # 130tps in 1s buckets
quota: 39000 # 130tps
quotaInterval: 1
quotaTimeUnit: minute
