name: application-restricted # Will have SERVICE_NAME- prepended to this
displayName: Personal Demographics Service - Application Restricted
description: Access the Personal Demographics Service with reduced permisions.
environments:
  - prod
  - ref
attributes:
  - name: access
    value: public
  - name: ratelimit
    value: 18000pm  # Approx 300ps, higher than quota to allow short burst loads
quota: 39000 # 130tps
quotaInterval: 5 # Smoothed to 5 limits to be kind to bursty loads
quotaTimeUnit: minute
