name: Build Jobs

on:
  push:
    branches:
      - 'APM-247-github-actions'

jobs:
  build:
    name: Deploy Revision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Update apt repositories
        run: sudo apt update

      - name: Install Java and Node
        run: sudo apt install default-jre default-jdk npm

      - name: Upgrade python packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install poetry
        run: pip install poetry

      - name: Install repo
        run: make install

      - name: Check licenses
        run: make check-licenses

      - name: Lint Spec
        run: make test

      - name: Check resources are valid FHIR 4.0.1
        run: make validate

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: validation.txt
          path: /tmp/validation.txt

      - name: Compile spec
        run: make publish

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          path: ./dist/patient-demographics-service-api.json

      - name: Deploy to Apigee (if master)
        run: scripts/deploy.sh
