name: Build

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # This causes all history to be fetched, which is required for calculate-version to function

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Update apt repositories
        run: sudo apt update

      - name: Install Java and Node
        run: sudo apt-get install --yes default-jre default-jdk npm

      - name: Upgrade python packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install poetry
        run: pip install poetry

      - name: Cache poetry packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install repo
        run: make install

      - name: Start local sandbox server
        run: |
          cd sandbox
          npm run start &

      - name: Check licenses
        run: make check-licenses

      - name: Lint
        run: make lint

      - name: Check resources are valid FHIR 4.0.1
        run: make validate

      - name: Compile spec
        run: make publish

      - name: Set SPEC_VERSION env var
        run: echo ::set-env name=SPEC_VERSION::$(poetry run python scripts/calculate_version.py)

      - name: Run local tests
        env:
          API_TEST_ENV_FILE_PATH: "tests/e2e/environments/local.postman_environment.json"
        run: make test

      - name: Copy local test report
        if: always()
        run: cat newman/*.html > dist/local-tests.html && rm newman/*.html

      - name: Store local test result artifact
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: local-tests-${{ env.SPEC_VERSION }}+${{ github.run_id }}.html
          path: ./dist/local-tests.html

      - name: Store distributable schema
        uses: actions/upload-artifact@v1
        with:
          name: patient-demographics-service-api-${{ env.SPEC_VERSION }}+${{ github.run_id }}.json
          path: ./dist/patient-demographics-service-api.json
