name: Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  teardown:
    name: Teardown
    runs-on: ubuntu-latest
    steps:
      - name: Kickoff teardown pipeline
        run: |
          curl -X POST "https://dev.azure.com/NHSD-APIM/API%20Platform/_apis/build/builds?api-version=5.0" \
               -H "Authorization: Basic $(echo ${{ secrets.AZURE_DEVOPS_USER }} | base64):${{ secrets.AZURE_DEVOPS_TOKEN }}" \
               -H "Content-Type: application/json; charset=utf-8" \
               -d "{\"definition\": {\"id\": \"24\"}, \"parameters\": {\"TEARDOWN_BRANCH\": \"$GITHUB_REF\"}}" \
               --fail -v
