name: Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  teardown:
    name: Teardown
    runs-on: ubuntu-latest
    steps:
      - name: Kickoff teardown pipeline
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: "https://dev.azure.com/NHSD-APIM/API Platform"
          azure-pipeline-name: "PDS API Pull Request Teardown"
          azure-devops-token: "${{ secrets.AZURE_DEVOPS_TOKEN }}"
