name: Lint PR
on: pull_request
jobs:
  link-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Check ticket name is in pull request
        run: echo {{ github.ref }} | grep -i -E -q "apm-[0-9]+"
